### ISSUE TITLE
Paper formatting

### ISSUE THREAD

**Issue by barneydobson** [dbdespot/pysewer#10]
- Indentation at L57-63, I think should be in line with the margin?
- L66 - I guess this is inaccurate as DEM should be in `.tif` not `.shp` (or similar)

**Comment by ddspot** [comment]
I adjusted the wording of the sentence, indicating the DEM format as `.shp`. It now reads more clearly, and the vector(`.shp`, `geojson`, `.gpkg`)  and raster (`.tif`) formats are more obvious. Thank you for pointing that out. Finally, the indentation is also now adjusted.
