### ISSUE TITLE
data validation and guidance

### ISSUE THREAD

**Issue by barneydobson** [dbdespot/pysewer#4]
Some way to validate the user-provided data seems necessary both to ensure people use the software correctly, and to help them debug their data:

i.e., some way to check the values (and particularly the graph):

```yaml
custom_config.preprocessing.dem_file_path
custom_config.preprocessing.buildings_input_data
custom_config.preprocessing.roads_input_data
```

It also needs to be explained clearly in the documentation what is needed from this data.

**Comment by ddspot** [comment]
Thanks, @barneydobson. You made an excellent point here. To provide a better idea of how the input data should be, we provided an example of how those input data (geodataframes) should be and specifically included the required relevant columns, along with the data type and description. In addition, I have added data validation in preprocessing.py, which provides a more strict checking to ensure that the gdfs are in the form outlined in the updated [README.md.](https://github.com/dbdespot/pysewer/blob/main/README.md) under the section input data requirements. Just so you know, I have added a notebook with a quick check using a subset of your data, see #7.
