### ISSUE TITLE
documentation link broken

### ISSUE THREAD

**Issue by barneydobson** [dbdespot/pysewer#6]
The link to the notebook from the main page is broken

https://github.com/dbdespot/pysewer/blob/main/notebooks/example_sewer_network_generation.ipynb

I guess it should be:
https://github.com/dbdespot/pysewer/blob/main/notebooks/example_sewer_network.ipynb

**Comment by ddspot** [comment]
@barneydobson, you are absolutely correct; thanks for pointing this out. This is now corrected.
