### ISSUE TITLE
Fails using own data

### ISSUE THREAD

**Issue by barneydobson** [dbdespot/pysewer#7]
Thought it would be sensible to test this with my own data. I can't get it to work and I can't figure out why - I assume primarily because more information on the format of the user-provided data is needed. May be helpful with more validation (see #4 )

The code I used to run it is and data is [here](https://github.com/user-attachments/files/17279730/pysewer.zip) :
```python
import pysewer
from pysewer.config.settings import load_config  # load the the settings file 

# load custom settings from the example settings file
custom_config = load_config("")
custom_config.preprocessing.dem_file_path = r"C:\Users\bdobson\Documents\data\temp\pysewer\elevation.tif"


custom_config.preprocessing.roads_input_data = r"C:\Users\bdobson\Documents\data\temp\pysewer\roads.geojson"


custom_config.preprocessing.buildings_input_data =r"C:\Users\bdobson\Documents\data\temp\pysewer\buildings.geojson"

# Instantiate the model domain
test_model_domain = pysewer.ModelDomain(
    dem=custom_config.preprocessing.dem_file_path,
    buildings=custom_config.preprocessing.buildings_input_data,
    roads=custom_config.preprocessing.roads_input_data,
    clustering="centers",
    # pump_penalty=custom_config.preprocessing.pump_penalty,
    pump_penalty=1000,
)
```

It produces the error below:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[18], line 23
     20 custom_config.preprocessing.buildings_input_data =r"C:\Users\bdobson\Documents\data\temp\pysewer\buildings.geojson"
     22 # Instantiate the model domain
---> 23 test_model_domain = pysewer.ModelDomain(
     24     dem=custom_config.preprocessing.dem_file_path,
     25     buildings=custom_config.preprocessing.buildings_input_data,
     26     roads=custom_config.preprocessing.roads_input_data,
     27     clustering="centers",
     28     # pump_penalty=custom_config.preprocessing.pump_penalty,
     29     pump_penalty=1000,
     30 )

File ~\AppData\Local\miniforge3\envs\pysewer\Lib\site-packages\pysewer\preprocessing.py:504, in ModelDomain.__init__(self, dem, roads, buildings, clustering, pump_penalty, connect_buildings)
    502 if len(sub_graphs) > 1:
    503     print("connecting subgraphs")
--> 504     self.connect_subgraphs()
    506 # set pump penalty
    507 self.pump_penalty = pump_penalty

File ~\AppData\Local\miniforge3\envs\pysewer\Lib\site-packages\pysewer\preprocessing.py:913, in ModelDomain.connect_subgraphs(self)
    907 G_without_sg_gdf = get_node_gdf(G_without_sg).unary_union
    909 # check if either gdf is empty or contains invalid values
    910 if (
    911     sg_gdf.is_empty
    912     or G_without_sg_gdf.is_empty
--> 913     or sg_gdf.isna().any()
    914     or G_without_sg_gdf.isna().any()
    915 ):
    916     warnings.warn(
    917         "Skipped an iteration: Empty or invalid subgraph detected...Skipping this connection."
    918     )
    919     continue

```

**Comment by ddspot** [comment]
Thanks for sharing the sample data and reporting this issue. To fix this, I needed to improve the handling of nans. However, when using your data, I found that the lowest elevation (default sink) was at the border of the elevation (see figure below). Having the road and building data to the edge of the DEM causes problems, such as points with missing elevation values. I have added some recommendations in the [README.md](https://github.com/dbdespot/pysewer/blob/main/README.md) to avoid the issues arising from the boundaries. Essentially, one must ensure:
- that the roads and buildings data are clipped to the area of interest, i.e. the settlement area.
- that the DEM covers the area of interest. For example, if the planned WWTP is located outside of the city, then this area must be included in the DEM.
- The DEM must be free of no-data values, i.e., all the DEM should be inspected and undergo quality check before being used.
- that all additional sinks are within the bounds of the DEM. 

To complete the test with your data, I used a reduced area to speed things up. Please see the following notebook [here](https://github.com/user-attachments/files/17350343/from_reviewer.zip). Finally, I have added some details on the data input and guidance as specified in issue #4, also in the updated [README.md](https://github.com/dbdespot/pysewer/blob/main/README.md).
![image](https://github.com/user-attachments/assets/1581d226-670a-4db4-9bf5-cdf632c0eb0a)

**Comment by barneydobson** [comment]
this is much clearer - happy to close
