### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by barneydobson** [dbdespot/pysewer#8]
I thought to fix #6 but it seems I would need to fork the repo - the way that others are expected to contribute to the software should be explained in [CONTRIBUTING.md](https://github.com/dbdespot/pysewer/blob/main/CONTRIBUTING.md).

**Comment by ddspot** [comment]
The [CONTRIBUTING.md](https://github.com/dbdespot/pysewer/blob/main/CONTRIBUTING.md) is now updated and includes a section on forking and pull requests. We added a small note on the permissions and the main branch. I hope that it is more clear for those who want to contribute.
